### ISSUE TITLE
Questions about google Colab Package problem

### ISSUE THREAD

**Issue by ericliwaseda** [FangYang970206/MaskRCNN-Keypoint-Demo#1]
Directly Use Your demo on Colab will cause this problem when download the pakeages:

ERROR: google-colab 1.0.0 has requirement six~=1.12.0, but you'll have six 1.13.0 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.

So what should I do to Reduced version and compatible to colab?

**Comment by FangYang970206** [comment]
Hi, I updated the demo.ipynb to adapt colab, run the new version. Thank you for submitting the issue.
